# coding: utf-8

# flake8: noqa
"""
    CarbonAware.WebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.carbon_intensity_batch_parameters_dto import CarbonIntensityBatchParametersDTO
from openapi_client.models.carbon_intensity_dto import CarbonIntensityDTO
from openapi_client.models.emissions_data import EmissionsData
from openapi_client.models.emissions_data_dto import EmissionsDataDTO
from openapi_client.models.emissions_forecast_batch_parameters_dto import EmissionsForecastBatchParametersDTO
from openapi_client.models.emissions_forecast_dto import EmissionsForecastDTO
from openapi_client.models.location import Location
from openapi_client.models.validation_problem_details import ValidationProblemDetails
