# coding: utf-8

"""
    CarbonAware.WebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.emissions_data_dto import EmissionsDataDTO

class TestEmissionsDataDTO(unittest.TestCase):
    """EmissionsDataDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EmissionsDataDTO:
        """Test EmissionsDataDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EmissionsDataDTO`
        """
        model = EmissionsDataDTO()
        if include_optional:
            return EmissionsDataDTO(
                location = 'eastus',
                timestamp = '2022-06-01T14:45Z',
                duration = 30,
                value = 359.23
            )
        else:
            return EmissionsDataDTO(
        )
        """

    def testEmissionsDataDTO(self):
        """Test EmissionsDataDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
