# coding: utf-8

"""
    CarbonAware.WebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.carbon_intensity_batch_parameters_dto import CarbonIntensityBatchParametersDTO

class TestCarbonIntensityBatchParametersDTO(unittest.TestCase):
    """CarbonIntensityBatchParametersDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CarbonIntensityBatchParametersDTO:
        """Test CarbonIntensityBatchParametersDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CarbonIntensityBatchParametersDTO`
        """
        model = CarbonIntensityBatchParametersDTO()
        if include_optional:
            return CarbonIntensityBatchParametersDTO(
                location = 'eastus',
                start_time = '2022-03-01T15:30Z',
                end_time = '2022-03-01T18:30Z'
            )
        else:
            return CarbonIntensityBatchParametersDTO(
        )
        """

    def testCarbonIntensityBatchParametersDTO(self):
        """Test CarbonIntensityBatchParametersDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
