# coding: utf-8

"""
    CarbonAware.WebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.emissions_forecast_batch_parameters_dto import EmissionsForecastBatchParametersDTO

class TestEmissionsForecastBatchParametersDTO(unittest.TestCase):
    """EmissionsForecastBatchParametersDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EmissionsForecastBatchParametersDTO:
        """Test EmissionsForecastBatchParametersDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EmissionsForecastBatchParametersDTO`
        """
        model = EmissionsForecastBatchParametersDTO()
        if include_optional:
            return EmissionsForecastBatchParametersDTO(
                requested_at = '2022-06-01T00:03:30Z',
                location = 'eastus',
                data_start_at = '2022-03-01T15:30Z',
                data_end_at = '2022-03-01T18:30Z',
                window_size = 30
            )
        else:
            return EmissionsForecastBatchParametersDTO(
        )
        """

    def testEmissionsForecastBatchParametersDTO(self):
        """Test EmissionsForecastBatchParametersDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
