# coding: utf-8

# flake8: noqa

"""
    CarbonAware.WebAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.carbon_aware_api import CarbonAwareApi
from openapi_client.api.locations_api import LocationsApi

# import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiAttributeError
from openapi_client.exceptions import ApiException

# import models into sdk package
from openapi_client.models.carbon_intensity_batch_parameters_dto import CarbonIntensityBatchParametersDTO
from openapi_client.models.carbon_intensity_dto import CarbonIntensityDTO
from openapi_client.models.emissions_data import EmissionsData
from openapi_client.models.emissions_data_dto import EmissionsDataDTO
from openapi_client.models.emissions_forecast_batch_parameters_dto import EmissionsForecastBatchParametersDTO
from openapi_client.models.emissions_forecast_dto import EmissionsForecastDTO
from openapi_client.models.location import Location
from openapi_client.models.validation_problem_details import ValidationProblemDetails
